blank_issues_enabled: true
contact_links:
  - name: Questions / Discussions
    url: https://github.com/aliansoftwareteam/AlianHub-Project-Management-System/issues/discussions
    about: Please ask questions here
